### ISSUE TITLE
Catch/Handle/Fix the ValueError in gpg keyinit

### ISSUE THREAD

**Issue by f-breidenstein** [aurblobs/aurblobs#11]
```
(aurblobs-BPVIV4sw) flanders aurblobs [master●] python -m aurblobs init testrepo /home/fleaz/aurblobs/testrepo foo@bar.com
Unable to create basedir, no write permissions.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fleaz/.local/share/virtualenvs/aurblobs-BPVIV4sw/lib/python3.6/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/home/fleaz/.local/share/virtualenvs/aurblobs-BPVIV4sw/lib/python3.6/site-packages/gnupg/_parsers.py", line 1351, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'KEY_CONSIDERED'

```

**Comment by mweinelt** [comment]
Upstream issue in python-gnupg package.

Fix was already pull requested on 2017/10/17 https://github.com/isislovecruft/python-gnupg/pull/212

**Comment by mweinelt** [comment]
I have updated and tested the dependency and lgtm.

```
% python -m aurblobs init repo ~/tmp/aurblobs-repository aurblobs@aurblobs.local
	usermod: no changes
	gpg: directory '/home/build/.gnupg' created
	gpg: keybox '/home/build/.gnupg/pubring.kbx' created
	gpg: /home/build/.gnupg/trustdb.gpg: trustdb created
	gpg: key 119087701F88D693: public key "repo repository key (insecure!) <aurblobs@aurblobs.local>" imported
	gpg: key 119087701F88D693: secret key imported
	gpg: Total number processed: 1
	gpg:               imported: 1
	gpg:       secret keys read: 1
	gpg:   secret keys imported: 1
	==> Creating updated database file 'repo.db.tar.gz'
	==> WARNING: No packages remain, creating empty database.
	==> Signing database 'repo.db.tar.gz'...
	  -> Created signature file 'repo.db.tar.gz.sig'
	==> WARNING: No packages remain, creating empty database.
	==> Signing database 'repo.files.tar.gz'...
	  -> Created signature file 'repo.files.tar.gz.sig'
Repositry successfully initialized.
```
