### ISSUE TITLE
Make sure the container exists, and inform more beautiful if it does not

### ISSUE THREAD

**Issue by mweinelt** [aurblobs/aurblobs#3]
- [ ] container build logic
  - build if it does not exist
  - build if Dockerfile changed
- [ ] exception handling

```
% aurblobs update test  
loading config: /home/hexa/.config/aurblobs/test.json
loading state: /home/hexa/.cache/aurblobs/test.json
uade PKGBUILD updated from None to ec7d0a9460b6bf8f8a01d5f8196c496273e8ab40
Building uade...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/home/hexa/.local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.30/containers/create?name=aurblobs_uade_18-04-1512234261

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 715, in run
    detach=detach, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 766, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 449, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 460, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 228, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: aurblobs-build:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/home/hexa/.local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.30/images/create?fromImage=aurblobs-build

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hexa/.local/bin/aurblobs", line 11, in <module>
    load_entry_point('aurblobs', 'console_scripts', 'aurblobs')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hexa/git/hexa/aurblobs/aurblobs/cli.py", line 81, in update
    pkg.update(force)
  File "/home/hexa/git/hexa/aurblobs/aurblobs/package.py", line 61, in update
    self.build(pkgroot)
  File "/home/hexa/git/hexa/aurblobs/aurblobs/package.py", line 100, in build
    signing_key: {'bind': '/privkey.gpg', 'mode': 'ro'}
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 717, in run
    self.client.images.pull(image)
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 280, in pull
    self.client.api.pull(name, tag=tag, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/image.py", line 393, in pull
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for aurblobs-build, repository does not exist or may require 'docker login'")
```

**Comment by f-breidenstein** [comment]
Fixed in 416b402276930e17c21f9ed5cc6b47b86e258489
