### ISSUE TITLE
PKGBUILD Git repository may need to be discovered

### ISSUE THREAD

**Issue by mweinelt** [aurblobs/aurblobs#31]
**Example:**
The Eiskalt DCPP client is a single PKGBUILD split into six subpackages.

- https://aur.archlinux.org/packages/eiskaltdcpp-qt-git/
- https://aur.archlinux.org/packages/eiskaltdcpp-gtk-git/
- https://aur.archlinux.org/packages/eiskaltdcpp-data-git/
- https://aur.archlinux.org/packages/eiskaltdcpp-daemon-git/
- https://aur.archlinux.org/packages/eiskaltdcpp-core-git/
- https://aur.archlinux.org/packages/eiskaltdcpp-cli-git/

The problem is that currently aurblobs will happily configure any of those packages and then during `update` it will choke because the git repository doesn't exist at the URL it thinks it does.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/aurpkg/aurblobs/aurblobs/__main__.py", line 6, in <module>
    cli()
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/lib/aurpkg/aurblobs/aurblobs/cli.py", line 125, in update
    pkgcache=pkgcache
  File "/var/lib/aurpkg/aurblobs/aurblobs/package.py", line 90, in update
    head = str(pkgrepo.head.commit)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/git/refs/symbolic.py", line 192, in _get_commit
    obj = self._get_object()
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/git/refs/symbolic.py", line 185, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/git/refs/symbolic.py", line 127, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/git/refs/symbolic.py", line 176, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/git/refs/symbolic.py", line 159, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

The git repository uses the following name: https://aur.archlinux.org/eiskaltdcpp-git.git

Can we use css selectors to parse the information from the AUR package details page?
`#pkginfo > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > a:nth-child(1)`

Or is there a better way?

**Comment by fooker** [comment]
What about specifying the `pkgbase` instead of `pkgname` during `aurblobs add`. Using this one could use the git repo (`https://aur.archlinux.org/${pkgbase}.git`) to for checks?

**Comment by mweinelt** [comment]
We can get the `pkgbase` from the `pkgname`, and save the `pkgbase` (and tell the user about it). That would be my preferred way to handle this.
